default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  min_messages: warning
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  database: nada_faces_api_development

test:
  <<: *default
  database: nada_faces_api_test
